#!/usr/bin/sh

compile() {
    echo ----- Compiling Day $1 -----
    time v $AOC_ROOT/src/$1.v -o $AOC_ROOT/bin/$1
}

if [[ ! -d $AOC_ROOT/bin ]];
then
    mkdir -p $AOC_ROOT/bin
fi;

for i in $@;
    do
        day=$(printf "%02d" $i)
        compile $day
    done;
