#!/usr/bin/sh

solve() {
    echo ----- Solving Day $1 -----
    time $AOC_ROOT/bin/$1 < $AOC_ROOT/data/$1.in
}

if [[ ! -d $AOC_ROOT/bin ]];
then
    echo "No binaries present. Invoke 'compile' script first."
    exit
fi;

if [[ ! -d $AOC_ROOT/data ]];
then
    echo "No $AOC_ROOT/data present. Invoke 'download-data' script first."
    exit
fi;

for i in $@;
    do
        day=$(printf "%02d" $i)
        solve $day
    done;
